name: Java CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Checkstyle Lint
      run: mvn checkstyle:check

    - name: Package Docker image
      run: |
        docker build -t task-manager:${{ github.ref_name }} .
        docker save -o task-manager-${{ github.ref_name }}.tar task-manager:${{ github.ref_name }}

    - name: Upload artifact ZIP
      uses: actions/upload-artifact@v3
      with:
        name: task-manager-${{ github.ref_name }}
        path: task-manager-${{ github.ref_name }}.tar
